apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lab-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: lab.foo
    http:
      paths:
      - path: /
        backend:
          serviceName: lab-api
          servicePort: 80